--!strict
-- spell-checker: disable

local Types = require(script.Parent.Types)

--[[ 
	Few things of note:
	- There is ZERO organization or formatting here, I legit just pulled a random list of Staff IDs to ban.
	- We excluded a number of people we knew were not bioluminescent, so if you made this list, maybe re-evaluate the people you align yourself with.
	- New hires are not added due to how irrelevant they are.
	- Don't take the comments as gospel, I was TRYING to be funny with these. Lol, lmao even.
	- The entire repository is a joke and meant to poke fun. Thank you for coming to my Ted Talk.
	- Signed, Subazen "Gnarly" "GNX" "Gnarl Gnarx" Bones
]]
return {
	-- 93745294, -- D3vision
	546596150, -- ivri - 40 year old divorced electrician with 3 kids - UPDATE: It appears I was mistaken with my initial assessment of this individual, and for that I humbly apologize for my transgressions. He is actually a 50 year old divorced electrician with 7 kids.
	484782977, -- Dev - Shay's E-Kitten
	14491710, -- Wingz - Kept a google document that contained all of the Stylis Staff Member's heights and other personal info, even tried to get their shoe size at one point
	3361361336, -- Wingz
	1141343202, -- Wingz
	79207006, -- Ennrax - Was hardly active from what I've heard
	25258278, -- NatalieStarr - Derlefa disciple
	72572415, -- NatalieStarr
	866714226, -- Willow - bah
	968686896, -- Jo1tic - Mild case of Serious Brain Damage
	562083773, -- DragonHeart - CCP loyalist or something
	152450103, -- Opera/Calico_Mar - Said Muhammed was a terrorist name and had to leave the discord because of it. Immediately joined back on an alt and stylis gave him his staff perms back. Masterful gambit.
	2707290406, -- N3ght
	205631503, -- PuppyLover99191
	68818303, -- Knevf - was trial staff for 6 months LMFAOOOOO
	403050959, -- JKiller - some random from aus
	5064852410, -- JKiller alt
	153704791, -- Vel/Neondragon1177
	334009865, -- Redd_forman
	1319607361, -- Redd alt
	146205517, -- Reimbrandt/Obsoleity
	122620627, -- Mr Nobody
	43996023, -- Mr Nobody
	543539816, -- 2_Pyy
	398822200, -- RandomZachOfKindness
	22987728, -- Aidan/AxfulUwU
	202380951, -- 99Glxcks
	2703173908, -- Ghos7Luke - KDR HERO
	2381885386, -- Ghos7Luke alt
	49055023, -- JeavenXX - One of the people of all time
	3713953111, -- Jeaven alt
	571150649, -- Qumpus - random aus mod
	3584074637, -- Qumpus alt
	53275569, -- FlareonFlarez/Ann Martinet
	1675057829, -- Ann alt
	1158253396, -- 58 Classics - Cyberstalked TyIer_FB/8ar in game just to kick him for going OoB in transit
	4542129842, -- 58 Classics alt
	73157973, -- Werner
	1490264654, -- Werner alt
	99109156, -- Shuppin - Shuppin
	9690348, -- ninj
	4541361323, -- ninj alt
	161330729, -- Ava/EvilDelusions
	79623245, -- Wyrins - aus game mod
	12054426, -- wyrins alt
	60439930, -- BiggiePrawns
	2801217128, -- prawns alt
	309915008, -- LuLu_id
	218220788, -- Gavin910
	179462103, -- benistoocool
	36484441, -- Gurlony - what a name
	172512160, -- Bravothedragon/Raii
	14843530, -- Dragoon/00kamiMio - I know a vtuber fan when I see one (literally me)
	53337015, -- Faith/cater46
	28553019, -- Zane/vialsofblood
	341741270, -- LaptopMasterRace
	668428, -- DuoDeca - "YOU COULD HAVE FIT IN SO WELL WITH THE INNER CIRCLE GNX, YET YOU CHOSE THIS PATH"
	3550812845, -- duo alt
	4533152492, -- duo alt
	99865168, -- Urban
	2602495617, -- Urban alt
	87975168, -- Blind/Zenk0i
	2286384838, -- blind alt
	5697615, -- Antifuse/Zachary - Apparently one of the more respectable people on the admin team but I can't really confirm that so oh well
	46095074, -- Antifuse alt
	29754124, -- Nubbly - Made their STYLIS STUDIOS SPECIFIC Discord profile cropped fetish porn and when asked to change it they made it DIFFERENT cropped porn. Like seriously
	23657007, -- Lionehh
	927576600, -- Lionehh alt
	380346096, -- Miner - Stylis misread his name and hired him instantly
	76765030, -- Blasteroid17 - just a little bit of a dunce (or so I've heard)
	3527694664, -- Blasteroid alt
	3961287389, -- Blasteroid alt
	622542939, -- Papper2K
	84269600, -- GotMaxis
	3229432143, -- Forza/sub2justme2
	4459087542, -- forza alt
	290528530, -- Vanguard - FREE MY BOY DERLEFA HE AINT DUN NUN !!!!
	4539265546, -- Vanguard alt
	4117498958, -- Vanguard alt
	745935533, -- Ralphdawg
	94364254, -- Aquaaa_Cpt
	42574928, -- Navy.gif - bot manager for stylis. They run the Galactic QA moderation bot
	73654327, -- Culprits
	981497571, -- Culprits alt
	68324769, -- Ruminary - someone
	1882559549, -- Ruminary
	1549215911, -- Ruminary
	16903820, -- Ellie/Tengeki - someone
	63496342, -- Arktiica - someone
	1719107188, -- Arktiica
	3470675179, -- Arktiica
	81872846, -- WiViW - kinda chill but not really
	3709250431, -- WiViW
	164754297, -- Ruby - Some random they hired that spoke in full grammar and was pretty obnoxious to talk to
	4060370722, -- Ruby
	2854006756, -- Ruby
	47716569, -- Activix
	92983292, -- Activix
	119900911, -- Miss In Tent
	1766962461, -- Miss In Tent
	1842171624, -- Miss In Tent
	237307660, -- SteveTheSteve
	52986476, -- nickocat
	2812589440, -- nickocat
	2616564129, -- Drew_unfakE
	237476305, -- Static
	3295343531, -- Static
	610221248, -- Debbb
	2383900675, -- Debbb
	191662084, -- High_Sea
	2025711644, -- High_Sea
	19469248, -- Naexie
	111245805, -- Naexie
	1187769867, -- DevToby
	3535881357, -- DevToby
	85950035, -- UnholyKaty - ukelele melee
	36394540, -- ShadowSentinal - SCL Head
	17333293, -- Nausica_DesWindes - "Hardly a child predator if they're not actively seeking kids and were instead approached by the kid"
	1208433805, -- Valltony
	3926259390, -- Valltony
	55378857, -- TJ/CursedOnes
	988071501, -- DartTheQueen
	4380898896, -- DartTheQueen
	859442963, -- Tyler_S - (not 8ar) Whole fucking can of worms, admitted to me while we were playing forza in VC once that he hooked up with a 16 year old irl and also ERPed with 16 yo TyIer_FB/8ar. He was 19.
	1782796727, -- Tyler_S
	4332889557, -- Tyler_S
	335194103, -- CrimsonAlpha
	2040535683, -- CrimsonAlpha
	31250608, -- BusyCityGuy
	178624716, -- Shrimpjak
	1174568424, -- 42ndParadigm
	217484720, -- Ragteros - You do not want to know.
	8573949, -- weirdking
	6708673, -- weirdking
	41503661, -- alphytm - rank 100 club addict that got caught saying bad words in game chat
	473205846, -- Chaos
	4263559679, -- Chaos
	173391644, -- Eggss - apparently resigned but didn't get emeritus. unlucky ig
	781842863, -- Sevenilja
	514093618, -- Sevenilja alt
	4670292914, -- NanachiWithAGlock - I don't know if this person actually did anything but they were besties with derlefa and their name comes from a loli gore fetish manga so that's something

	--[[ -- Celest
		260 on the RAADS-R test that prides herself on having a fuckload of accounts on roblox just to cyberstalk a modded PF build that nobody can actually play.
		Frequently treated the Stylis Developers' words as gospel until Stylis were aired out. 
		These were all the accounts we could find in, uh
		*checks watch*
		3 minutes. Give or take. Search for yourself it's almost impressive. Almost.
	]]
	{ UserId = 1093633609, DisplayReason = 'the high priestess of litoism' }, -- Celest main
	{ UserId = 2380823843, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 2380815081, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 1280396571, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 3403489526, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 3956300415, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 3952480856, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 2380812536, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 2380815743, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 2380819126, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 2380819665, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 1969262856, DisplayReason = 'the high priestess of litoism' }, -- Celest alt
	{ UserId = 2380820327, DisplayReason = 'the high priestess of litoism' }, -- Celest alt

	-- Custom
	{ UserId = 3543904142, DisplayReason = '571' }, -- Derlefa - Ticked every box on how to NOT behave online. Sent NSFW to a group of minors, Some of the content involved the austrian painter, regular user of racial slurs, Tried talking to a 13 year old. Spawned the 571 meme by saying the hard R 571 times in one message.
	{ UserId = 66366193, DisplayReason = 'alaskan crab fishing extraordinaire' }, -- Cid9 - free ChatGPT-o1 in dms
	{ UserId = 31137804, DisplayReason = 'how many terabytes you got?' }, -- Raspy - legend says he's still patching Lito's code to this day
	{ UserId = 1667819, DisplayReason = 'burger king' }, -- shaylan007 - busy playing steam games for 1000h a week
	{ UserId = 525919, DisplayReason = 'mousepad' }, -- AxisAngle - nesting code indents like he's building the Great Pyramid of Giza
	{ UserId = 5725475, DisplayReason = 'am i clean?' }, -- Lito - "You LIED about Mar, you LIED about being clean." - Godstatus 2025 🙏
	{ UserId = 23602315, DisplayReason = 'active liability' }, -- Poodros - Responsible for maps like Farmlands and bragged about having over 300 maps archived for being terrible. Went on Spirals' stream to try and defend his "boss" lito (LMFAOOOOO) and fumbled miserably.
	{ UserId = 32631909, DisplayReason = 'god told me so' }, -- VictorReznov345 - Actual manchild that had a tantrum over Rialag being a better, quicker modeller than him and even called him unemployed as an excuse for his skill. Rialag is a teenager in school dude, get a fucking grip. Also posted a thirst trap in #rank-100-club for some fucking reason.

	--[[ -- Lexeris
		Basically inserted herself as the new "head of balance" after Willow left and was genuinely the most insufferable person to talk to about balance. 
		Would outright ignore you Lito- style if you didn't agree with her balance decisions and would constantly claim I was strawmanning her whenever I would 
		make predictions about how her shitty balance would turn out (which were almost always right).
	]]
	{ UserId = 1260619, DisplayReason = 'i listen to problems not solutions' }, -- Lexe_ris

	--[[ -- HAL/BattleWiner
		Hundreds of messages of him calling known underage users within the Stylis Studios discord "lolis" had surfaced, along with OTHER messages of him saying that he's ATTRACTED to "lolis."
		One of these people he spoke to, chels, later went on to get in trouble for sending a video of them yacking it federal style to a minor on discord once they were over 18.
		As some of you may know, the very concept of grooming means to manipulate the victim into believing deplorable actions and behaviour are "normal" in order to either illicit reciprocated behaviour
		or extort explicit material out of the victim. This is all to say, WHERE did chels learn that it was ok to send themselves gherkin it no pickle to a minor?

		Completely unrelated to above but he also whiteknighted a vtuber when they played phantom forces on stream to 1k people which is pretty funny.
	]]
	{ UserId = 40158790, DisplayReason = 'put the pallet on the forklift bro' },
	1912590065, -- HAL alt

	-- Deleted
	-- 62028759, -- PyralisFire - deleted their account lol
} :: { Types.CustomBanConfig }
